### ISSUE TITLE
setupDecompWorkspace and Idea not doing their job

### ISSUE THREAD

**Issue by InfinityRaider** [PhoenixTeamMC/PhoenixMod#1]
Permission to replace the build script with mine and as I go along with it update forge?

**Comment by Elec332** [comment]
I honestly dont see the problem:
http://i.imgur.com/JIWCTDI.png

EDIT: that was setupDevWorkspace, but setupDecompWorkspace IDEA also seems to be working fine:
http://i.imgur.com/3z6ok5P.png

Maybe some of the servers where the assets were pulled from were down? (Try again now? ;))

**Comment by InfinityRaider** [comment]
setupDecompWorkspace Idea did'nt work for me, I swapped it with my buildscript and it worked fine
